### ISSUE TITLE
Image generation result altered when using Compel embeddings

### ISSUE THREAD

**Issue by alexisrolland** [damian0815/compel#1]
Hello,

I am using `compel==0.1.2` to generate embeddings, which I pass to `diffusers==0.12.1` pipeline `StableDiffusionPipeline` using the model [IlluminatiAI/Illuminati_Diffusion_v1.0](https://huggingface.co/IlluminatiAI/Illuminati_Diffusion_v1.0). It seems the result generated with embeddings is completely altered compared to when using regular text. 

Example:
- prompt: a fantasy landscape with a mountain in background
- steps: 50
- guidance: 6
- seed: -245604080
- scheduler: DPMSolverMultistepScheduler

Image with prompt as text:
![Promp As Text](https://i.imgur.com/6msWlbZ.png)

Image with prompt embeddings:
![Promp Embeddings](https://i.imgur.com/fXFAzgI.png)

I'm not sure whether this is a problem with Compel or the model itself but I thought I would let you know.

**Comment by damian0815** [comment]
oh that's very interesting. i'll have a look into it, i appreciate the heads-up.

**Comment by damian0815** [comment]
@alexisrolland would you mind checking latest main here and see if that fixes your problem?

```
pip uninstall compel
pip install git+http://github.com/damian0815/compel
```

**Comment by alexisrolland** [comment]
Hello @damian0815 and thank you for the prompt answer. It seems it is fixed with that last version. I get the same image! Note that I did not encounter this issue with other models. I'm wondering why it happens with this one specifically?

**Comment by damian0815** [comment]
> Hello @damian0815 and thank you for the prompt answer. It seems it is fixed with that last version. I get the same image! Note that I did not encounter this issue with other models. I'm wondering why it happens with this one specifically?

it's an SD2 thing. in SD1 the pad and eos tokens were the same, in SD2 pad is a different token. keturn on invoke actually found and fixed it, i just had been lazy about updating compel.
