### ISSUE TITLE
Meaning of '+' and '-'

### ISSUE THREAD

**Issue by CheeseInTrap** [damian0815/compel#12]
Hi, I am using this repository in diffusers to weight prompt, but I have a question about the meaning of signature '+' and '-' . 

1. Does a '+' mean add 10% weight to the last word before it ? For example, "a red cat playing with a ball++" works like "a red cat playing with a (ball:1.2)" in AUTOMATIC1111 webui . I find this explanation on reddit, but there is no official doc having same description
2. Does "(ultra detailed face)+++" add weight to whole content in ()?

**Comment by damian0815** [comment]
@CheeseInTrap The prompting uses the same syntax as InvokeAI - https://invoke-ai.github.io/InvokeAI/features/PROMPTS/#prompt-syntax-features

**Comment by CheeseInTrap** [comment]
Thanks a lot!
