### ISSUE TITLE
Error with Blend + withLoRA

### ISSUE THREAD

**Issue by hipsterusername** [damian0815/compel#17]
withLoRA outside blend:

> 
pyparsing.exceptions.ParseException: Expected {explicit_conjunction | {{blend | Group:([{cross_attention_substitute | lora | attention | Forward: string enclosed in '"' | parenthesized_fragment | free_word | Suppress:(<SP><TAB><CR><LF>)}]...)} StringEnd}}, found 'withLora'  (at char 483), (line:1, col:484)

Errors out inside the blend as well.

**Comment by damian0815** [comment]
should be fixed with 1.1.0
