### ISSUE TITLE
How to use Compel with list of prompts

### ISSUE THREAD

**Issue by alexisrolland** [damian0815/compel#2]
The current quick start code snippet shows how to use Compel for a single text prompt:

```py
# upweight "ball"
prompt = "a cat playing with a ball++ in the forest"
conditioning = compel.build_conditioning_tensor(prompt)

# generate image
image = pipeline(prompt_embeds=conditioning, num_inference_steps=20).images[0]
```

Considering diffusers accept a list of text prompts, what would be the expected syntax for a list of prompts / prompts embeddings?

I have tried the following which does not work, but that seems to be an issue with `StableDiffusionPipeline`, not with `Compel`:

```
prompts = ["a cat playing with a ball++ in the forest", "a cat playing with a ball in the forest"]

compel = Compel(tokenizer=pipeline.tokenizer, text_encoder=pipeline.text_encoder)
prompt_embeds = []
for prompt in prompts:
    prompt_embed = compel.build_conditioning_tensor(prompt)
    prompt_embeds.append(prompt_embed)
```

**Comment by damian0815** [comment]
i suspect that will need to be a torch tensor rather than a list - so rather than 1x77x767 it will need to be 2x77x768 if you have 2 prompt strings. torch.cat is your friend here but it can take some getting used to the syntax

**Comment by damian0815** [comment]
@alexisrolland this works:
```
compel = Compel(tokenizer=pipeline.tokenizer, text_encoder=pipeline.text_encoder)
prompt_embeds = torch.cat([compel.build_conditioning_tensor(prompt) for prompt in prompts])
images = pipeline(prompt_embeds=prompt_embeds).images
```

**Comment by patrickvonplaten** [comment]
Also slightly related: https://github.com/damian0815/compel/pull/4#issuecomment-1456074008
