### ISSUE TITLE
Clarification needed: `Token indices sequence length is longer ...` during inference

### ISSUE THREAD

**Issue by detkov** [damian0815/compel#20]
Versions
```
compel==1.1.0
diffusers==0.15.0.dev0
```

Reproduction code sample:
```python
from diffusers import StableDiffusionPipeline
from compel import Compel

pipeline = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")
compel = Compel(tokenizer=pipeline.tokenizer, text_encoder=pipeline.text_encoder)

prompt = 25 * "a cat playing with a ball in the forest"
negative_prompt = 25 * "ugly, blurry, out of focus "

prompt_embeds = compel.build_conditioning_tensor(prompt)
negative_prompt_embeds = compel.build_conditioning_tensor(negative_prompt)

prompt_embeds, negative_prompt_embeds = compel.pad_conditioning_tensors_to_same_length(
    conditionings=[prompt_embeds, negative_prompt_embeds]
)

images = pipeline(prompt_embeds=prompt_embeds, negative_prompt_embeds=negative_prompt_embeds)
```

During this, I encounter the following message:
```
Token indices sequence length is longer than the specified maximum sequence length for this model (227 > 77). Running this sequence through the model will result in indexing errors
```
So I have those questions:
1) Do I understand it right, that I can just ignore this?
2) How can I stop this message from being printed?
3) Where does it came from?

Thanks in advance

**Comment by damian0815** [comment]
Interesting, i haven't seen that before. Is it happening on one of the calls to `compel.build_conditioning_tensor()` or does it only appear at `pipeline()`? In any case because Compel was not initialized with `truncate_long_prompts=False,` the token sequence ought to be being truncated to the correct length before it gets passed to `pipeline` (which means the call to `pad_conditioning_tensors_to_same_length()` is unnecessary).

**Comment by detkov** [comment]
I'm sorry, I just forgot to paste the `truncate_long_prompts=False,` into the initialization of `compel`.

Dependencies:
```
diffusers==0.14.0
compel==1.1.0
```

Code, can be run in the colab with GPU:
```python
from diffusers import StableDiffusionPipeline
from compel import Compel
import torch

pipeline = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", 
                                                   safety_checker=None,
                                                   requires_safety_checker=False,
                                                   feature_extractor=None,
                                                   torch_dtype=torch.float16).to('cuda')

compel = Compel(tokenizer=pipeline.tokenizer, text_encoder=pipeline.text_encoder, 
                truncate_long_prompts=False)

prompt = 25 * "a cat playing with a ball in the forest"
negative_prompt = 25 * "ugly, blurry, out of focus "

prompt_embeds = compel.build_conditioning_tensor(prompt)
negative_prompt_embeds = compel.build_conditioning_tensor(negative_prompt)

prompt_embeds, negative_prompt_embeds = compel.pad_conditioning_tensors_to_same_length(
    conditionings=[prompt_embeds, negative_prompt_embeds]
)

images = pipeline(prompt_embeds=prompt_embeds, negative_prompt_embeds=negative_prompt_embeds)
```
Similarly, I have `Token indices sequence length is longer than the specified maximum sequence length for this model (227 > 77). Running this sequence through the model will result in indexing errors` in the output. I don't understand, because it seems like if I use the `truncate_long_prompts=False`, I shouldn't see messages like this.

**Comment by damian0815** [comment]
Is the error happening on one of the calls to `compel.build_conditioning_tensor()` or does it only appear at `pipeline()`? if it's only happening at `pipeline()` then this is entirely expected - the long prompt is a hack and it shouldn't work (i don't use it fwiw, it's provided based on user demand)

**Comment by detkov** [comment]
This happens on `compel.build_conditioning_tensor()`

**Comment by damian0815** [comment]
i spent some time looking into this, it is in fact an expected warning. token sequences longer than 77 tokens are not a supported usage of the stable diffusion model (i assume you're using SD) - that it works at all is a quirk.

**Comment by damian0815** [comment]
@BEpresent you can pass an argument, i think it's `truncate=False`, to Compel `__init__` and it will turn of truncation

**Comment by BEpresent** [comment]
thanks, just for clarification, would the `.and()` syntax work also with the conditioning tensors and they would be passed in in chunks ?


So instead of this
```
        conditioning = self.compel.build_conditioning_tensor(long_prompt)
        negative_conditioning = self.compel.build_conditioning_tensor(long_negative_prompt)
        conditioning, negative_conditioning = self.compel.pad_conditioning_tensors_to_same_length([conditioning, negative_conditioning]) 
```



Something like this?
```
        conditioning = self.compel.build_conditioning_tensor(("a b c", "d, e f").and())
        negative_conditioning = self.compel.build_conditioning_tensor(("a b c", "d, e f").and())
        conditioning, negative_conditioning = self.compel.pad_conditioning_tensors_to_same_length([conditioning, negative_conditioning]) 
```

**Comment by damian0815** [comment]
close you need to put the '.and()' inside the prompt string:  `self.compel.build_conditioning_tensor('("a b c", "d, e f").and()')`

compel has methods to count tokens, you can call `compel.describe_tokenization()` or `compel.get_tokens()` and check the lenght of the returned arrays. note though that this does not account for syntax - if you call `compel.get_tokens()` on a prompt like `a cat++ playing with a ball` the `++` will be included as two extra tokens, whereas when you run compel "for real" they will be applied and removed from the token sequence
