### ISSUE TITLE
Blending not working as expected

### ISSUE THREAD

**Issue by kirillrogovoy** [damian0815/compel#25]
Let's take any incorrect blending section such as `("foo", "bar").blend(0.1,0.2,0.7)` (words/weights mismatch).

If that's the only thing the prompt consists of, compel throws an error — correct.

If the prompt starts with this section and then has more stuff, compel throws an error — correct.

If this section is anywhere in the middle of the prompt, compel doesn't throw an error — **unexpected**.

Also, from a bunch of experimentation, it seems like compel simply ignores the section in that case.

Since the doc doesn't mention anything about positions in the prompt, I did expect blending to work anywhere.

So, I expect this prompts to fail, but it doesn't:
```
a man on the ("moon", "earth").blend(0.5,0.5,0.5), walking
```

As the extension of it, even if I write a correct blending section, it doesn't seem like it's actually applied:
```
a man on the ("moon", "earth").blend(0.5,0.5), walking
```

**Comment by damian0815** [comment]
blends are only applied to the entire prompt. because CLIP accepts unstructured input, Compel tries not to throw errors if it doesn't recognise the syntax, and instead passes the string untouched through to CLIP. 

i'm open to changing this around blends in particular, though. given that in-situ blends aren't going to be supported any time soon (the math doesn't work out), what would you like to have happen in the last case?

**Comment by kirillrogovoy** [comment]
Ah, got it, so the only working option is when the blend construct is the only thing in the prompt, right?

I've been experimenting with making consistent characters like [here](https://www.reddit.com/r/StableDiffusion/comments/12djxvz/how_to_create_consistent_character_faces_without/)

They refer to a1111 blending when using `[concept1|concept2]` and that's what I've been trying to reproduce with diffusers+compel. The syntax itself doesn't matter to me much, but I thought that it would be great to embed the blending construct inside the prompt.

I guess, with my previous example, the right version is this?
```
("a man on the moon, walking", "a man on the earth, walking").blend(0.5,0.5)
```

I could pro-process my prompts to achieve that, but it's going to be tedious and most users might need to roll their own solution for that since writing these blending constructs where most of each variation is the identical is cumbersome.

Unless I'm missing something again about how it works currently.

**Comment by damian0815** [comment]
right, the a111 blend is a completely different implementation that works by oscillating between the terms on subsequent frames. the compel blend mathematically lerps the embeddings together then used the same embedding all the way through the generation process.

**Comment by damian0815** [comment]
so they’re not at all equivalent. i have plans for a scheduling feature that would enable the oscillation effect but idk when/if i’ll have time to implement it any time soon

**Comment by kirillrogovoy** [comment]
Got it, thanks for the explanation!

Then maybe it makes sense to mention this is the docs since more people would associate blending in compel with a1111.

I mean the fact that it only works if there's nothing else in the prompt.

As far as I understand, right now oscillating between prompts on different steps is not possible without forking StableDiffusionPipeline, because there's no API to allow for that, and the denoising loop is located inside of StableDiffusionPipeline.

Would it work if we just calculate multiple [prompt_embeds](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L637-L645) before the loop based on different variations of the prompt and then oscillate between them when calculating the [noise residual](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L676-L681) inside the loop? Or is it more nuanced than that?

**Comment by damian0815** [comment]
yes, that's right. yes the blend docs are a bit sparse. i'll get to the them at some point 🙈

> Would it work if we just calculate multiple [prompt_embeds](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L637-L645) before the loop based on different variations of the prompt and then oscillate between them when calculating the [noise residual](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L676-L681) inside the loop? Or is it more nuanced than that?

That ought to be enough, yes, although it might be worth looking at the auto11 implementation to confirm that they're not doing something special on early or late diffusions steps to resolve any instabilities.
