### ISSUE TITLE
Understanding prompt weighting asymmetry 

### ISSUE THREAD

**Issue by jrhe** [damian0815/compel#26]
I am trying to understand why there is an asymmetry between the up and down weights applied to prompts, with the up weights being stronger.

---; --; -; ; +; ++; +++ give weights of 0.729; 0.81; 0.9; 1; 1.1; 1.21; 1.331 respectively, with the positive prompts diverging from 1 than the negative prompts, and the negative prompts never converging fully to 0. 

Mathematically I understand the asymmetry, but why is this favoured over a symmetrical sequence on either side of one? e.g. 0.669, 0.79, 0.9; 1; 1.1; 1.21; 1.331.

I expect this may be to do with the asymmetry in the weighting of the underlying embeddings, e.g. using tanh on those <1, but don't fully understand that code either yet.

**Comment by damian0815** [comment]
the weights don't really have much of a meaning. ++ should feel stronger than +, and -- should feel stronger than -. note that in practise upweighting tops out at about 1.6 (depending on CFG) and causes noise/distorted generations. but this depends on the token being up or downweighted - `cat` likely tops out quicker than something more obscure.

**Comment by jrhe** [comment]
That makes sense. The info on where things typically top out is pretty useful so I have added it to `Reference.md` in a PR.

I guess my point is that intuitively --/++, ---/+++, etc, should feel like they are doing the inverse yet they aren't balanced. The latent space they are working on isn't linear/stable so it probably doesn't make a massive difference, but it might be worth considering making them balanced anyway.

**Comment by damian0815** [comment]
i'm gonna close this
