### ISSUE TITLE
Textual inversion with diffusers

### ISSUE THREAD

**Issue by pdoane** [damian0815/compel#28]
I would like to get Compel working with the textual inversion and Diffusers.  I am able to get good results if I use the TextualInversionManager from InvokeAI but I don't want to add that as a dependency.

It looks like the pad tokens added in expand_textual_inversion_token_ids_if_necessary are critical.  Do you have any suggestions for how to proceed?

**Comment by damian0815** [comment]
if you're using embeddings with a vector size of 1 then Compel doesn't need to get involved at all, they should just work OOTB. 

if you have embeddings with a vector size of >1, say n=4, then you need some way of expanding the single trigger token into slots for 4 embeddings (the trigger token + 3 extras). compel/TextualInversionManager does this basically by exploding the vector size `4` TI into 4 x vector size `1` TI's.

**Comment by pdoane** [comment]
Thanks!  The context there was very useful.  Here's an implementation of a TextualInversionManager that works with the pad tokens that diffusers create:

```
class DiffusersTextualInversionManager(BaseTextualInversionManager):
    def __init__(
        self,
        loader: TextualInversionLoaderMixin,
        tokenizer: CLIPTokenizer,
    ):
        self.loader = loader
        self.tokenizer = tokenizer

    def expand_textual_inversion_token_ids_if_necessary(
        self, prompt_token_ids: list[int]
    ) -> list[int]:
        if len(prompt_token_ids) == 0:
            return prompt_token_ids

        prompt = self.tokenizer.decode(prompt_token_ids)
        tokens = self.tokenizer.tokenize(prompt)
        for token in tokens:
            if token in self.tokenizer.added_tokens_encoder:
                replacement = token
                i = 1
                while f"{token}_{i}" in self.tokenizer.added_tokens_encoder:
                    replacement += f" {token}_{i}"
                    i += 1

                prompt = prompt.replace(token, replacement)

        return self.tokenizer.encode(prompt, add_special_tokens=False)
```

It would be nice to not go back and forth between text and tokens, but the data structures aren't setup for that yet.  Maybe this would be interesting to include in Compel?

**Comment by pdoane** [comment]
There is a bug in diffusers that I'm working to resolve now.  After that is merged, the above can be simplified:

```
class TextualInversionManager(BaseTextualInversionManager):
    def __init__(
        self,
        loader: TextualInversionLoaderMixin,
        tokenizer: CLIPTokenizer,
    ):
        self.loader = loader
        self.tokenizer = tokenizer

    def expand_textual_inversion_token_ids_if_necessary(
        self, prompt_token_ids: list[int]
    ) -> list[int]:
        if len(prompt_token_ids) == 0:
            return prompt_token_ids

        prompt = self.tokenizer.decode(prompt_token_ids)
        prompt = self.loader.maybe_convert_prompt(prompt, self.tokenizer)
        return self.tokenizer.encode(prompt, add_special_tokens=False)
```

**Comment by pdoane** [comment]
I'm closing the issue out as this is resolved.  Having a class in Compel or example in documentation could be useful for future devs - happy to make a PR here if you'd like.

**Comment by damian0815** [comment]
yes please PR would be great :)

**Comment by alexisrolland** [comment]
Hi @pdoane , @damian0815 ,

I'm trying to get textual inversion embeddings working in combination with compel and failing to do so.
- When I keep Compel implementation, the embedding does not have any effect
- When I remove Compel and use the prompt directly for inference then the embedding works

Would you have a minimal example that uses Compel and TI embeddings together please?
Thanks!

Here is what I've got:

```py
[...]
# Load Stable Diffusion model for text-to-image
MODEL_PATH = os.getenv('MODEL_PATH')
pipeline = StableDiffusionPipeline.from_pretrained(MODEL_PATH, torch_dtype=torch.float16, revision="fp16", safety_checker=safety_checker, feature_extractor=feature_extractor)
pipeline .enable_model_cpu_offload()
pipeline .enable_xformers_memory_efficient_attention()

# Load textual inversion embeddings
EMBEDDING_PATH = os.getenv('EMBEDDING_PATH')
pipeline .load_textual_inversion(EMBEDDING_PATH, token='charturnerv2')

[...]

# Convert prompt to embedding
compel = Compel(tokenizer=pipeline.tokenizer, text_encoder=pipeline.text_encoder)
prompt_embeds = compel(prompts)

[...]
result = pipeline(
        prompt_embeds=prompt_embeds,
        negative_prompt_embeds=negative_prompt_embeds,
        width=width,
        height=height,
        num_inference_steps=steps,
        guidance_scale=guidance,
        num_images_per_prompt=1,
        generator=generators
    )
```

I use Compel as bellow

**Comment by damian0815** [comment]
@alexisrolland if your prompt includes `charturnerv2` and it has vector length=1 then it should just work, no need to do anything extra.

**Comment by damian0815** [comment]
oh you may have to use a different word than `charturnerv2` , see this comment: https://github.com/huggingface/diffusers/issues/3097#issuecomment-1516140736

**Comment by alexisrolland** [comment]
Thanks @damian0815 but how can I know if my prompt has a vector length >1? I have used the implementation you linked to enforce charturnerv2 as trigger word, and then I'm just using compel as described above to convert a list of prompts into embeddings.

**Comment by pdoane** [comment]
@damian0815 - charturnerv2 has vector length=15 and needs a manager like the one I provided in the PR.  It would be helpful to get that merged and then I can put a PR on the diffusers website to update the Compel examples.

@alexisrolland - The easiest way to test if you are working with a multi-vector embedding is to use `pipe.maybe_convert_prompt(prompt, pipe.tokenizer)`

```
>>> print (pipe.maybe_convert_prompt('charturnerv2', pipe.tokenizer))

charturnerv2 charturnerv2_1 charturnerv2_2 charturnerv2_3 charturnerv2_4 charturnerv2_5 charturnerv2_6 charturnerv2_7 charturnerv2_8 charturnerv2_9 charturnerv2_10 charturnerv2_11 charturnerv2_12 charturnerv2_13 charturnerv2_14
```

For multi-vector embeddings, diffusers creates a number of special tokens of the form `f"{token}_{i}"`

**Comment by alexisrolland** [comment]
> It would be helpful to get that merged and then I can put a PR on the diffusers website to update the Compel examples.

+1 for this, it would be fantastic!

**Comment by alexisrolland** [comment]
Honestly at this point I don't know what I'm doing but for some reason it seems this worked! I have just added  `prompts = pipeline.maybe_convert_prompt(prompts, pipeline.tokenizer)` before converting the prompts to embeddings with Compel.

```
[...]
# Load model
MODEL_PATH = os.getenv('MODEL_PATH')
pipeline = StableDiffusionPipeline.from_pretrained(MODEL_PATH, torch_dtype=torch.float16, revision="fp16", safety_checker=safety_checker, feature_extractor=feature_extractor)
pipeline.enable_model_cpu_offload()
pipeline.enable_xformers_memory_efficient_attention()

# Load textual inversion embedding
EMBEDDING_PATH = os.getenv('EMBEDDING_PATH')
pipeline.load_textual_inversion(EMBEDDING_PATH, token='charturnerv2')

[...]

# Convert prompt to embedding
compel = Compel(tokenizer=pipeline.tokenizer, text_encoder=pipeline.text_encoder)
prompts = pipeline.maybe_convert_prompt(prompts, pipeline.tokenizer)
prompt_embeds = compel(prompts) # Where prompts is an array of strings containing charturnerv2

[...]
result = pipeline(
    prompt_embeds=prompt_embeds,
    negative_prompt_embeds=negative_prompt_embeds,
    width=width,
    height=height,
    num_inference_steps=steps,
    guidance_scale=guidance,
    num_images_per_prompt=1,
    generator=generators
)
```

**Comment by pdoane** [comment]
`maybe_convert_prompt` does work in many situations but it isn't robust.  Consider having a multi-vector textual inversion named `abc` and a lora named `abc.safetensors`,  the prompt `"withLora(abc.safetensors, 1)"` will be incorrectly converted by `maybe_convert_prompt` but this works when going through the textual inversion manager interface.

You can also just copy my implementation until the PR is merged.  It's not that many lines of code :)
