### ISSUE TITLE
Lora in prompt

### ISSUE THREAD

**Issue by alexblattner** [damian0815/compel#30]
Hello, I trained a lora with [name] as its name. this would normally (in A1111) ensure that when you reference it with <lora:(name of the file without extension):1> it would work in the prompt. How can you achieve the same?

**Comment by damian0815** [comment]
`withLora(name, weight)` or `useLora(name, weight)` but compel does not handle loading/injecting the actual LoRA weights into the model. check how InvokeAI does it.

**Comment by alexblattner** [comment]
actually, I have code for context:

```
import torch
from safetensors.torch import load_file
from collections import defaultdict
def load_lora_weights(pipeline, checkpoint_path, multiplier, device, dtype):
    LORA_PREFIX_UNET = "lora_unet"
    LORA_PREFIX_TEXT_ENCODER = "lora_te"
    # load LoRA weight from .safetensors
    state_dict = load_file(checkpoint_path, device=device)

    updates = defaultdict(dict)
    for key, value in state_dict.items():
        # it is suggested to print out the key, it usually will be something like below
        # "lora_te_text_model_encoder_layers_0_self_attn_k_proj.lora_down.weight"

        layer, elem = key.split('.', 1)
        updates[layer][elem] = value

    # directly update weight in diffusers model
    for layer, elems in updates.items():

        if "text" in layer:
            layer_infos = layer.split(LORA_PREFIX_TEXT_ENCODER + "_")[-1].split("_")
            curr_layer = pipeline.text_encoder
        else:
            layer_infos = layer.split(LORA_PREFIX_UNET + "_")[-1].split("_")
            curr_layer = pipeline.unet

        # find the target layer
        temp_name = layer_infos.pop(0)
        while len(layer_infos) > -1:
            try:
                curr_layer = curr_layer.__getattr__(temp_name)
                if len(layer_infos) > 0:
                    temp_name = layer_infos.pop(0)
                elif len(layer_infos) == 0:
                    break
            except Exception:
                if len(temp_name) > 0:
                    temp_name += "_" + layer_infos.pop(0)
                else:
                    temp_name = layer_infos.pop(0)

        # get elements for this layer
        weight_up = elems['lora_up.weight'].to(dtype)
        weight_down = elems['lora_down.weight'].to(dtype)
        alpha = elems['alpha']
        if alpha:
            alpha = alpha.item() / weight_up.shape[1]
        else:
            alpha = 1.0

        # update weight
        if len(weight_up.shape) == 4:
            curr_layer.weight.data += multiplier * alpha * torch.mm(weight_up.squeeze(3).squeeze(2), weight_down.squeeze(3).squeeze(2)).unsqueeze(2).unsqueeze(3)
        else:
            curr_layer.weight.data += multiplier * alpha * torch.mm(weight_up, weight_down)

    return pipeline


import torch
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel, UniPCMultistepScheduler,ModelMixin
from io import BytesIO
from PIL import Image
import torch.multiprocessing as mp
import Loras
controlnet = ControlNetModel.from_pretrained("lllyasviel/control_v11p_sd15_openpose", torch_dtype=torch.float16)
print(1)
pipe = StableDiffusionControlNetPipeline.from_pretrained(
  "runwayml/stable-diffusion-v1-5", controlnet=controlnet, torch_dtype=torch.float16,safety_checker=None, requires_safety_checker=False,
).to("cuda")
pipe=Loras.load_lora_weights(pipe, 'mngstle.safetensors',1.0,'cuda',torch.float16)
print(2)
pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config)

pipe.enable_xformers_memory_efficient_attention()
pipe.enable_model_cpu_offload()
print(3)
buffer=open('gpose.png', 'rb')
buffer.seek(0)
image_bytes = buffer.read()
images = Image.open(BytesIO(image_bytes))
generator = torch.manual_seed(1)
prompt="art by <lora:mngstle:1>"
n_prompt="(nsfw), out of frame, multiple people, petite, loli, side view, profile, lowres, (bad anatomy, bad hands:1.1), text, (tattoo), error, missing fingers, extra digit, fewer digits, cropped, worst quality, (((many people))), low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name,weird colors, (cartoon, 3d, bad art, poorly drawn, close up, blurry:1.5), (disfigured, deformed, extra limbs:1.5)"
fimage=pipe(
    prompt,
    images,
    negative_prompt=n_prompt,
    num_inference_steps=20,
    generator=generator,
)
fimage = fimage.images[0]
fimage.save('result.png', format='PNG')
```

the first part is a lora loader and the second is a somewhat traditional implementation of diffusers controlnet.

where would withLora(name, weight) or useLora(name, weight) come in?

**Comment by damian0815** [comment]
`nsfw` and `loli` uhh

**Comment by alexblattner** [comment]
> `nsfw` and `loli` uhh. no, you won't be getting any support from me.

It's n_prompt dude... It's negative prompt! I'm literally ensuring the opposite! @damian0815

**Comment by damian0815** [comment]
ahhhaa sorry! overreaction on my part

**Comment by damian0815** [comment]
right if you replace `art by <lora:mngstle:1>` with uhh... uhhh.. i don't know how auto111 prompts work, but i believe that actually will resolve to `art by` and the lora gets loaded? anyway if you change it to `art by withLora(mngstle,1)` and then instead of just using `compel(prompt)` you'd do `Compel.parse_prompt_string(cls, prompt_string: str)` which returns a `Conjunction` and on that you can read off the `LoraWeight` instances

**Comment by alexblattner** [comment]
> ahhhaa sorry! overreaction on my part
it's ok, mistakes happen and fuck pedos

> you wouldn't believe the prompts people submit as bug reports on InvokeAI 🙈
I wouldn't be surprised, but they are the ones improving the tech a lot though...




> right if you replace `art by <lora:mngstle:1>` with uhh... uhhh.. i don't know how auto111 prompts work, but i believe that actually will resolve to `art by` and the lora gets loaded? anyway if you change it to `art by withLora(mngstle,1)` and then instead of just using `compel(prompt)` you'd do `Compel.parse_prompt_string(cls, prompt_string: str)` which returns a `Conjunction` and on that you can read off the `LoraWeight` instances

would you mind giving a full code example just to be sure?

thanks for being patient, I really appreciate it

**Comment by damian0815** [comment]
how are you loading your LoRA files? do note that compel is not responsible for loading them on the model, all it does is parse the weights out of the prompt and return them to you in a handy data struct

**Comment by alexblattner** [comment]
I just use the load_lora_weights function in the code I shared above. Here is how I use the function:

```
controlnet = ControlNetModel.from_pretrained("lllyasviel/control_v11p_sd15_openpose", torch_dtype=torch.float16)
pipe = StableDiffusionControlNetPipeline.from_pretrained(
  "runwayml/stable-diffusion-v1-5", controlnet=controlnet, torch_dtype=torch.float16,safety_checker=None, requires_safety_checker=False,
).to("cuda")
pipe=Loras.load_lora_weights(pipe, 'mngstle.safetensors',1.0,'cuda',torch.float16)
```


I'll be honest, I don't understand how compel works with loras. Loras add themselves to the model (stable diffusion 1.5 in this case) and are not embeddings like textual inversion that merely teach words to the model. When you load loras without referencing them in the prompt, they already modify the final output.

You're the one who planned the equivalent to "<lora:koreanDollLikeness_v10:0.35>" which I don't know how it works. Would you mind elaborating somewhere how you do it? There's just a severe lack of information beyond figuring out the og code itself right now and would really appreciate clarifications.

**Comment by BEpresent** [comment]
> I just use the load_lora_weights function in the code I shared above. Here is how I use the function:
> 
> ```
> controlnet = ControlNetModel.from_pretrained("lllyasviel/control_v11p_sd15_openpose", torch_dtype=torch.float16)
> pipe = StableDiffusionControlNetPipeline.from_pretrained(
>   "runwayml/stable-diffusion-v1-5", controlnet=controlnet, torch_dtype=torch.float16,safety_checker=None, requires_safety_checker=False,
> ).to("cuda")
> pipe=Loras.load_lora_weights(pipe, 'mngstle.safetensors',1.0,'cuda',torch.float16)
> ```
> 
> I'll be honest, I don't understand how compel works with loras. Loras add themselves to the model (stable diffusion 1.5 in this case) and are not embeddings like textual inversion that merely teach words to the model. When you load loras without referencing them in the prompt, they already modify the final output.
> 
> You're the one who planned the equivalent to "lora:koreanDollLikeness_v10:0.35" which I don't know how it works. Would you mind elaborating somewhere how you do it? There's just a severe lack of information beyond figuring out the og code itself right now and would really appreciate clarifications.

I want to solve the same problem, seeing the discussion in https://github.com/huggingface/diffusers/issues/3064  .

While auto1111 might have some mechanism to load Loras just from parsing them in the prompts (I also have not looked into how exactly they are doing it) , I would assume that something similar to

`pipe=Loras.load_lora_weights(pipe, 'mngstle.safetensors',1.0,'cuda',torch.float16)` happens in the background? 

So whenever a Lora with the auto1111 syntax is mentioned in the prompt in Diffusers + Compel, it should be converted to some kind of `Loras.load_lora_weights`, at least this is probably how I would manually hack it together for the moment. 

The documentation states this `Compel.parse_prompt_string()` however I don't know what I should do with this, or what a conjunction is. Really grateful for your work @damian0815 don't get me wrong, but I would not be able to know how to use Loras (and may be this is not the intent of the library and it seems that the Diffusers team is actively working on a solution themselves)
<img width="870" alt="image" src="https://user-images.githubusercontent.com/7645717/234896473-a03e5c3a-303e-463c-8c2c-3fea563e6961.png">


What I use currently is just this from the documentation:

```
compel = Compel(..., truncate_long_prompts=False)
prompt = "a cat playing with a ball++ in the forest, amazing, exquisite, stunning, masterpiece, skilled, powerful, incredible, amazing, trending on gregstation, greg, greggy, greggs greggson, greggy mcgregface, ..." # very long prompt
conditioning = compel.build_conditioning_tensor(prompt)
negative_prompt = "" # it's necessary to create an empty prompt - it can also be very long, if you want
negative_conditioning = compel.build_conditioning_tensor(negative_prompt)
[conditioning, negative_conditioning] = compel.pad_conditioning_tensors_to_same_length([conditioning, negative_conditioning])
```

**Comment by damian0815** [comment]
* if you call `Compel.parse_prompt_string(prompt)` it will return a Conjunction:
```conjunction = Compel.parse_prompt_string(prompt)```

* the Conjunction has a `lora_weights` property:
```lora_weights = conjunction.lora_weights```

i don't know how to load LoRAs, so if you don't know how to use the `lora_weights` list I can't help you
