### ISSUE TITLE
Support regular LLMs

### ISSUE THREAD

**Issue by Hellisotherpeople** [damian0815/compel#33]
There is no reason why we can't utilize the same kind of techniques you show here on transformer models themselves. 

I even wrote a whole blog post which went viral on HN about this "undertooling" of LLMs compared to Stable Diffusion. https://gist.github.com/Hellisotherpeople/45c619ee22aac6865ca4bb328eb58faf

**Comment by damian0815** [comment]
i initially was excited about this idea but realised it's a bit beyond what i'm trying to do. the weighting strategy is pretty tightly coupled to SD's training on the last penultimate states. LLM prompting is a different ballgame, there are already different (and better) systems that compel out there.
