### ISSUE TITLE
Documentation: `.and()` feature needs `pad_conditioning_tensors_to_same_length()`

### ISSUE THREAD

**Issue by hqt98** [damian0815/compel#36]
I was trying out the new `and()` feature and it seems like the prompt pieces just get their embedding concatenated so dimension 77 becomes 154 for two pieces, 231 for 3 pieces and so on.

This gives the error `RuntimeError: The size of tensor a (154) must match the size of tensor b (77) at non-singleton dimension 1` during inference.

Is this a bug or am I using this new feature wrong? 
Thanks.

**Comment by bruefire** [comment]
I also encountered the same issue. 
By matching the number of negative prompts with the positive prompts, the error can be avoided. 

prompt: ("apple", "orange").and()
negative: ("", "").and()

**Comment by damian0815** [comment]
you can also run `[cond, negative_cond] = compel.pad_conditioning_tensors_to_same_length([cond, negative_cond])`
