### ISSUE TITLE
SDXL support

### ISSUE THREAD

**Issue by bghira** [damian0815/compel#37]
Trying to use the provided example with SDXL causes an error in Diffusers:

```
<class \'diffusers.models.unet_2d_condition.UNet2DConditionModel\'> has the config param `addition_embed_type` set to \'text_time\' which requires the keyword argument `text_embeds` to be passed in
```

is there a way you've determined that it might work, yet?

**Comment by damian0815** [comment]
interesting. i don't have access to SDXL weights so cannot really say anything, but yeah, it's sorta not surprising that it doesn't work. if you can get a hold of the two separate text encoders from the two separate models, you could try making two compel instances (one for each) and push the same prompt through each, then concatenate before passing on the unet. but i'm just guessing.

**Comment by bghira** [comment]
if you'd like to write up a small example, i can try it out.

**Comment by damian0815** [comment]
something like this:

```
pipeline = SDXLPipeline.from_pretrained(...)
base_model = pipeline.base_model # idk if/how you should do this
base_model = pipeline.refiner_model # 

compel_base = Compel(base_model.tokenizer, base_model.text_encoder)
compel_refiner = Compel(refiner_model.tokenizer, refiner_model.text_encoder)

prompt = "a cat playing with a ball in the forest"

embeds_base = compel_base(prompt)
embeds_refiner = compel_refiner(prompt)
embeds = torch.cat([embeds_base, embeds_refiner], dim=2)

images = pipeline(prompt_embeds=embeds, ...)
```

**Comment by damian0815** [comment]
@patrickvonplaten does the above look right?

**Comment by bghira** [comment]
it would be excellent @patrickvonplaten if we (the royal we, as in, you guys :D ) can update the call() function for SDXL to take the same parameter names, eg. prompt_embeds and negative_prompt_embeds. it is a constant issue for consistency where some have it plural or not, and i'd rather one less conditional be needed :pray:

**Comment by bghira** [comment]
@damian0815 the problem is that the base has two text encoders.

**Comment by damian0815** [comment]
ahh so it's not that simple. ok

**Comment by bghira** [comment]
I use this kind of wrapper class and have modified it to pull the Refiner's text encoder if it is found, so you can see how that works.

i will likely update this wrapper to handle a scenario whether there are two text encoders automatically, but i'm not yet certain how to form the returned embeds or how to pass them into the pipeline.

```python
from compel import Compel
from torch import Generator
import torch
class PromptManipulation:
    def __init__(self, pipeline, device, use_second_encoder: bool = False):
        self.is_valid_pipeline(pipeline)
        self.pipeline = pipeline
        if (use_second_encoder and self.has_dual_text_encoders(pipeline)) or (
            self.has_dual_text_encoders(pipeline) and self.is_sdxl_refiner(pipeline)
        ):
            # SDXL Refiner and Base can both use the 2nd tokenizer/encoder.
            pipe_tokenizer = self.pipeline.tokenizer_2
            pipe_text_encoder = self.pipeline.text_encoder_2
        else:
            # Any other pipeline uses the first tokenizer/encoder.
            pipe_tokenizer = self.pipeline.tokenizer
            pipe_text_encoder = self.pipeline.text_encoder

        self.compel = Compel(
            tokenizer=pipe_tokenizer,
            text_encoder=pipe_text_encoder,
            truncate_long_prompts=False,
            device="cuda",
            use_penultimate_clip_layer=True
        )

    def has_dual_text_encoders(self, pipeline):
        return hasattr(pipeline, "text_encoder_2")

    def is_sdxl_refiner(self, pipeline):
        # SDXL Refiner has the 2nd text encoder, only.
        if self.pipeline.tokenizer is None and hasattr(self.pipeline, "tokenizer_2"):
            return True
        return False

    def is_valid_pipeline(self, pipeline):
        if not hasattr(pipeline, "tokenizer") and not hasattr(
            pipeline, "tokenizer_2"
        ):
            raise Exception(
                f"Cannot use PromptManipulation on a model without a tokenizer."
            )

    def process(self, prompt: str):
        conditioning = self.compel.build_conditioning_tensor(prompt)
        return conditioning

    def process_long_prompt(self, positive_prompt: str, negative_prompt: str):
        if positive_prompt == "":
            positive_prompt = "since you did not provide a string, i will do it for you"
        conditioning = self.compel.build_conditioning_tensor(positive_prompt)
        negative_conditioning = self.compel.build_conditioning_tensor(negative_prompt)
        [
            conditioning,
            negative_conditioning,
        ] = self.compel.pad_conditioning_tensors_to_same_length(
            [conditioning, negative_conditioning]
        )

        return conditioning, negative_conditioning
```

**Comment by adhikjoshi** [comment]
Anyone got it working?

**Comment by patrickvonplaten** [comment]
See: https://github.com/damian0815/compel/pull/41

**Comment by bghira** [comment]
@damian0815 @patrickvonplaten it seems like num_inference_per_prompt is incorrectly handled.

```py
from compel import Compel, ReturnedEmbeddingsType
from diffusers import DiffusionPipeline
import torch

pipeline = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-0.9", use_safetensors=True, torch_dtype=torch.float16).to("cuda")
compel = Compel(truncate_long_prompts=False, tokenizer=[pipeline.tokenizer, pipeline.tokenizer_2] , text_encoder=[pipeline.text_encoder, pipeline.text_encoder_2], returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED, requires_pooled=[False, True])
# upweight "ball"
prompt = "a cat playing with a ball++ in the forest"
conditioning, pooled = compel(prompt)
# generate image
image = pipeline(prompt_embeds=conditioning, pooled_prompt_embeds=pooled, num_inference_steps=30, num_images_per_prompt=4).images[0]
```

output:

```
The size of tensor a (14400) must match the size of tensor b (3600) at non-singleton dimension 1
```

I am clever enough to realise that this is `3600 * 4 = 14400`

I tried to make a [list] of prompts, as I saw that the tensors would be concatenated when they are submitted in this way. However the same error occurs.

**Comment by bghira** [comment]
if I produce `compel([prompt] * batch_size)` embeds and pass them with `num_images_per_prompt=1` then I get a working result with multiple images! interesting. the other pipelines aren't like that, i assume the pipeline needs a issue report?

**Comment by BEpresent** [comment]
Question regarding long prompts+ negative prompts for SDXL and the use of the Refiner in combination with Compel: 

### 1: on build_conditioning_tensor and pad_conditioning_tensors_to_same_length

Here is some older SD1.5 code, Is `pad_conditioning_tensors_to_same_length` still needed? Would I need to chunk up long prompts to prevent truncation somehow using SDXL? 

```python
conditioning = compel.build_conditioning_tensor(prompt)
negative_conditioning = compel.build_conditioning_tensor(negative_prompt)
conditioning, negative_conditioning = compel.pad_conditioning_tensors_to_same_length([conditioning, negative_conditioning]) 
```


### 2: on Refiner Usage 

Sorry if this has been stated already: The pooled prompt embeds seem to be needed for the Refiner too ? I see some prototype code above by @bghira , I wonder if this is working?

Is it possible to have a short documentation on how to use the refiner + base model with very long prompts ?


The below was just a naive guess from me how and seems to work, using the tokenizer of the base model, or should I use the one from the refiner or doesn't it make a difference? The use of `text_encoder_2=pipeline.text_encoder_2` in the refiner definition suggests that they are indeed the same:

```python

from diffusers import DiffusionPipeline
import torch
from compel import Compel, ReturnedEmbeddingsType


use_refiner = True

pipeline = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
)
pipeline.to("cuda")

refiner = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-refiner-1.0",
    text_encoder_2=pipeline.text_encoder_2,
    vae=pipeline.vae,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16",
)
refiner.to("cuda")

compel = Compel(truncate_long_prompts=False, tokenizer=[pipeline.tokenizer, pipeline.tokenizer_2] , text_encoder=[pipeline.text_encoder, pipeline.text_encoder_2], returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED, requires_pooled=[False, True])

compel_refiner = Compel(truncate_long_prompts=False, tokenizer=pipeline.tokenizer_2 , text_encoder=pipeline.text_encoder_2, returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED, requires_pooled=[False, True])



conditioning_refiner, refiner_pooled_positive  = compel_refiner(prompt)
negative_conditioning_refiner , refiner_pooled_negative = compel_refiner(negative_prompt)


image_base = pipeline(prompt_embeds=conditioning, negative_prompt_embeds=negative_conditioning, pooled_prompt_embeds=pooled, negative_pooled_prompt_embeds=negative_pooled, num_inference_steps=30, output_type="latent" if use_refiner else "pil").images[0]

image = refiner(prompt_embeds=conditioning_refiner, negative_prompt_embeds=negative_conditioning_refiner, pooled_prompt_embeds=refiner_pooled_positive, negative_pooled_prompt_embeds=refiner_pooled_negative, num_inference_steps=30, image=image_base[None, :]).images[0]
```

**Comment by bghira** [comment]
@BEpresent i have updated my code there.

**Comment by damian0815** [comment]
sorry @BEpresent i've been unable to get SDXL working on my local system and haven't found time to setup a vast.ai remote debugging environment. i pushed compel 2.0.1 which should mean issues with `pad_conditioning_tensors_to_same_length` should work at least to generate an embedding of the right shape for the base model (`[1, 77, 2048]` or eg `[1, 154, 2048]` if you have a prompt needs 150 tokens instead of 75). if the refiner uses the same shape as the base then that should just work.

i just want to say to both of you though, @bghira and @BEpresent - i've been doing most of my experiments using SD2.1 and because it uses OpenCLIP, which is a more *precise* embedder, long prompts actually result in shittier generations. Since SDXL uses both OpenCLIP and OpenAI CLIP in tandem, you might want to try being more direct with your prompt strings - rather than just pooping out 10 million vague fuzzy tags, just write an english sentence describing the thing you want to see. OpenAI CLIP sucks at giving you that, but OpenCLIP is actually very good at it.

**Comment by bghira** [comment]
it's just got token bleed issues if you don't use prompt segmentation. i do not use long incoherent prompts, i use short ones, such as:

`('the pope', 'dressed as ronald mcdonald').and(0.9, 0.95)`

this tends to help overcome the imbalanced training data in the SDXL pile which ended up with heavier weights on certain subjects, making them inflexible.

**Comment by damian0815** [comment]
ahh i see @bghira so really what you're needing is the .and() support rather than truncating per se. that makes complete sense.

**Comment by damian0815** [comment]
i think i can close this..?
