### ISSUE TITLE
SDXL with non-truncated prompts results in error

### ISSUE THREAD

**Issue by bghira** [damian0815/compel#45]
This works:
```py
from compel import Compel, ReturnedEmbeddingsType
from diffusers import DiffusionPipeline
import torch

pipeline = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-0.9", use_safetensors=True, torch_dtype=torch.float16).to("cuda")
compel = Compel(truncate_long_prompts=False, tokenizer=[pipeline.tokenizer, pipeline.tokenizer_2] , text_encoder=[pipeline.text_encoder, pipeline.text_encoder_2], returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED, requires_pooled=[False, True])
prompt = "('a psychedelic style', 'cat playing in the forest').and()"
negative_prompt = "a test negative prompt that would be very short" 
prompt = [prompt] * 4
conditioning, pooled = compel(prompt)
negative_embed, negative_pooled = compel([negative_prompt] * 4)
[conditioning, negative_embed] = compel.pad_conditioning_tensors_to_same_length([conditioning, negative_embed])
# generate image
images = pipeline(prompt_embeds=conditioning, pooled_prompt_embeds=pooled, negative_prompt_embeds=negative_embed, negative_pooled_prompt_embeds=negative_pooled, num_inference_steps=30, num_images_per_prompt=1).images
images[0].save('/notebooks/test0.png')
images[1].save('/notebooks/test1.png')
images[2].save('/notebooks/test2.png')
images[3].save('/notebooks/test3.png')
```

This does not work:

```py
from compel import Compel, ReturnedEmbeddingsType
from diffusers import DiffusionPipeline
import torch

pipeline = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-0.9", use_safetensors=True, torch_dtype=torch.float16).to("cuda")
compel = Compel(truncate_long_prompts=False, tokenizer=[pipeline.tokenizer, pipeline.tokenizer_2] , text_encoder=[pipeline.text_encoder, pipeline.text_encoder_2], returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED, requires_pooled=[False, True])
prompt = "('a psychedelic style', 'cat playing in the forest').and()"
negative_prompt = "a test negative prompt that would be very long indeed and maybe we can blow past the seventy seven token limit and like, then we will see the error maybe? it is hard to say because the thing is hard to reproduce here in the standalone script, with the washed out and other studf that usuallyug esosouhfsldfh sldkf aldksfj glasdkjfg lasdkjfg laskdjfgh alsdkfg laskdhfjg alsdfg "
prompt = [prompt] * 4
conditioning, pooled = compel(prompt)
negative_embed, negative_pooled = compel([negative_prompt] * 4)
[conditioning, negative_embed] = compel.pad_conditioning_tensors_to_same_length([conditioning, negative_embed])
# generate image
images = pipeline(prompt_embeds=conditioning, pooled_prompt_embeds=pooled, negative_prompt_embeds=negative_embed, negative_pooled_prompt_embeds=negative_pooled, num_inference_steps=30, num_images_per_prompt=1).images
images[0].save('/notebooks/test0.png')
images[1].save('/notebooks/test1.png')
images[2].save('/notebooks/test2.png')
images[3].save('/notebooks/test3.png')
```

I'm not sure if there's something I'm doing wrong in this example, so, it's possible that the documentation simply needs an update.

**Comment by damian0815** [comment]
what is the exact error? 

i see you're doing a batch of 4, do you have the same problem with only one image in a batch?

**Comment by damian0815** [comment]
riiiight i see, the pooled embeddings have to be truncated.

i have pushed an exploratory fix to pypi, can you please try `pip install compel==2.0.0rc1`

**Comment by bghira** [comment]
```Token indices sequence length is longer than the specified maximum sequence length for this model (104 > 77). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (104 > 77). Running this sequence through the model will result in indexing errors
Traceback (most recent call last):
  File "/notebooks/SimpleTuner/inference/compel-test.py", line 13, in <module>
    [conditioning, negative_embed] = compel.pad_conditioning_tensors_to_same_length([conditioning, negative_embed])
  File "/notebooks/container/discord-tron-client/.venv/lib/python3.9/site-packages/compel/compel.py", line 258, in pad_conditioning_tensors_to_same_length
    return type(self)._pad_conditioning_tensors_to_same_length(conditionings, emptystring_conditioning=emptystring_conditioning)
  File "/notebooks/container/discord-tron-client/.venv/lib/python3.9/site-packages/compel/compel.py", line 234, in _pad_conditioning_tensors_to_same_length
    c = torch.cat([c, empty_z], dim=1)
RuntimeError: Tensors must have same number of dimensions: got 3 and 2```

**Comment by damian0815** [comment]
does this happen if you do a batch size of 1 instead of 4?

**Comment by damian0815** [comment]
i.e. instead of 
```
prompt = [prompt] * 4
conditioning, pooled = compel(prompt)
```
just do 
`conditioning, pooled = compel(prompt)`

**Comment by bghira** [comment]
yes, my last tests were all with batch size 1 after your request to do so

**Comment by bghira** [comment]
ah, looks like if instead of `[prompt]`, i use `prompt` as a parameter, it does not crash.

**Comment by bghira** [comment]
![image](https://github.com/damian0815/compel/assets/59658056/9490f1fc-dea8-4f86-87c2-e1b95d7f94ac)
but i do not think it is working correctly.

**Comment by bghira** [comment]
@damian0815 can you try using the first pooled embed vector rather than truncate them? ComfyUI does not truncate.

**Comment by damian0815** [comment]
sorry i don't know what you mean. the CLIP model only outputs 77 token embeddings. to build a longer embedding you have to actually subdivide the prompt into 75 token chunks and push each chunk through the text encoder separately.

**Comment by bghira** [comment]
well, honestly i haven't dealt with this code successfully in ways that you have. so your understanding is above and beyond mine. but my understanding is that the pooled embed somehow ends up at 104 tokens long here, in these earlier tests. and i'm not sure why that is, but i assumed it was some concatenation going on.

**Comment by Bochu3** [comment]
> riiiight i see, the pooled embeddings have to be truncated.
> 
> i have pushed an exploratory fix to pypi, can you please try `pip install compel==2.0.1rc1`

I have long prompt and short negative prompt wit truncate_long_prompts=False
I got error after update to 2.0.1rc1 
File "/opt/conda/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 692, in __call__
self.check_inputs(
File "/opt/conda/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 477, in check_inputs
raise ValueError(
ValueError: `prompt_embeds` and `negative_prompt_embeds` must have the same shape when passed directly, but got: `prompt_embeds` torch.Size([1, 154, 2048]) != `negative_prompt_embeds` torch.Size([1, 77, 2048]).

**Comment by damian0815** [comment]
> RuntimeError: Tensors must have same number of dimensions: got 3 and 2```

@bghira i just pushed 2.0.1 with a fix for this issue, you should now be able to run `pad_conditioning_tensors_to_same_length()` successfully, which means long prompts and also `.and()` should work.

please lmk if you're still having problems, i almost melted my 16GB Mac M1 loading the SDXL weights to test out text encoder, was too afraid to try actually generating anything.

**Comment by bghira** [comment]
checking

**Comment by bghira** [comment]
```
prompt = "a cat playing in the forest"
negative_prompt = "a test negative prompt that would be very long indeed"
```
# Published release 2.0.0:

**truncating = False**
base model only
![image](https://github.com/damian0815/compel/assets/59658056/b0b54bdb-01ae-41ec-8b2a-6f0c31f0317e)




**truncating = True**
base model
![image](https://github.com/damian0815/compel/assets/59658056/8294a9aa-1091-45d0-be20-bfd11ee1c026)
base model, but _**negative prompt is longer than token limit now**_
![image](https://github.com/damian0815/compel/assets/59658056/e7dc97e2-0b70-4cec-a6a3-b7d7f95305da)

**truncating = True**
base model
prompt is `('testing', 'this').and()`
```
    raise ValueError(f"All conditioning tensors must have the same batch size ({c0_shape[0]}) and number of embeddings per token ({c0_shape[1]}")
ValueError: All conditioning tensors must have the same batch size (1) and number of embeddings per token (77
```

# Latest test release:

**truncating = False**
base model only - **very long negative prompt that shows 150 > 77 token index warning**
![image](https://github.com/damian0815/compel/assets/59658056/6c36100a-8013-40e8-b2da-933172275b35)

**truncating = True**
base model with default, short prompts.
![image](https://github.com/damian0815/compel/assets/59658056/921be0ea-8f53-4dc1-8f21-c8ebddb2f885)

base model, but _**negative prompt is longer than token limit now**_
![image](https://github.com/damian0815/compel/assets/59658056/23c8f04c-2159-4043-a603-ba8ad7bd94c5)


**truncating = True**
base model
prompt is `('testing', 'this').and()`

**same error as before.**

```
    raise ValueError(f"All conditioning tensors must have the same batch size ({c0_shape[0]}) and number of embeddings per token ({c0_shape[1]}")
ValueError: All conditioning tensors must have the same batch size (1) and number of embeddings per token (77
```

**Comment by bghira** [comment]
```py
from compel import Compel, ReturnedEmbeddingsType
from diffusers import DiffusionPipeline
import torch

torch_seed = 123123123
torch.manual_seed(torch_seed)

# SDXL Base with DDIM scheduler, `trailing` timestep spacing.
pipeline = DiffusionPipeline.from_pretrained("ptx0/sdxl-base", use_safetensors=True, torch_dtype=torch.float16).to("cuda")
compel = Compel(
    truncate_long_prompts=True,
    tokenizer=[
        pipeline.tokenizer,
        pipeline.tokenizer_2
    ],
    text_encoder=[
        pipeline.text_encoder,
        pipeline.text_encoder_2
    ],
    returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED,
    requires_pooled=[
        False,
        True
    ]
)

prompt = 'a cat playing in the forest'
#prompt = "('testing', 'this').and()"
negative_prompt = "a test negative prompt that would be very long indeed" # and maybe we can blow past the seventy seven token limit and like, then we will see the error maybe? it is hard to say because the thing is hard to reproduce here in the standalone script, with the washed out and other studf that usuallyug esosouhfsldfh sldkf aldksfj glasdkjfg lasdkjfg laskdjfgh alsdkfg laskdhfjg alsdfg "

conditioning, pooled = compel(prompt)
negative_embed, negative_pooled = compel(negative_prompt)
[conditioning, negative_embed] = compel.pad_conditioning_tensors_to_same_length([conditioning, negative_embed])

base_strength = 0.50
num_inference_steps = 20
num_images_per_prompt = 1

# generate image
normal_images = pipeline(output_type='pil', num_inference_steps=num_inference_steps, num_images_per_prompt=num_images_per_prompt, width=1152, height=768,
                      prompt_embeds=conditioning, pooled_prompt_embeds=pooled, negative_prompt_embeds=negative_embed, negative_pooled_prompt_embeds=negative_pooled).images
normal_images[0].save('/notebooks/test0-base.png', format='PNG')
```

**Comment by damian0815** [comment]
it's hard to tell but with compel 2.0.1 the long prompt kinda looks a bit distorted and weird, yeah? honestly that's expected. long prompts should't work, they break the math.

**Comment by damian0815** [comment]
```   
 raise ValueError(f"All conditioning tensors must have the same batch size ({c0_shape[0]}) and number of embeddings per token ({c0_shape[1]}")
ValueError: All conditioning tensors must have the same batch size (1) and number of embeddings per token (77 ```
can you post the `.shape` of each the tensors you're passing to `pad_conditioning_tensors_to_same_length`?

**Comment by bghira** [comment]
yeah, that's expected because the prompt itself isn't even specifically asking for things that would make sense. for me, the issue is more that the `and` problem is still here.

**Comment by bghira** [comment]
```Conditioning shape: torch.Size([1, 77, 2048])
NConditioning shape: torch.Size([1, 77, 2048])
Pooled shape: torch.Size([1, 1280])
NPooled shape: torch.Size([1, 1280])```

**Comment by bghira** [comment]
```
prompt = "('testing', 'this').and()"
negative_prompt = "('a test negative prompt that would be very long indeed').and()"
```
equates to
```
Conditioning shape: torch.Size([1, 77, 4096])
NConditioning shape: torch.Size([1, 77, 2048])
Pooled shape: torch.Size([1, 1280])
NPooled shape: torch.Size([1, 1280])
```


```
prompt = "('testing', 'this').and()"
negative_prompt = "('a test negative prompt that would be very long indeed', '').and()"
```

brings:

```
Conditioning shape: torch.Size([1, 77, 4096])
NConditioning shape: torch.Size([1, 77, 2048])
Pooled shape: torch.Size([1, 1280])
NPooled shape: torch.Size([1, 1280])
```


and adding some text to the second segment on the negative, oddly didn't fix it:

```
Conditioning shape: torch.Size([1, 77, 4096])
NConditioning shape: torch.Size([1, 77, 2048])
Pooled shape: torch.Size([1, 1280])
NPooled shape: torch.Size([1, 1280])
```

**Comment by bghira** [comment]
reducing the positive prompt, down to `('testing').and()` while keeping the negative with >1 segment:


```
Conditioning shape: torch.Size([1, 77, 2048])
NConditioning shape: torch.Size([1, 77, 2048])
Pooled shape: torch.Size([1, 1280])
NPooled shape: torch.Size([1, 1280])
```

**Comment by bghira** [comment]
```py
prompt = "('testing', 'this').and()"
negative_prompt = prompt
```

brings:

```
Conditioning shape: torch.Size([1, 77, 4096])
NConditioning shape: torch.Size([1, 77, 4096])
Pooled shape: torch.Size([1, 1280])
NPooled shape: torch.Size([1, 1280])
```

**Comment by bghira** [comment]
```py
prompt = "('testing', 'this').and()"
negative_prompt = "('artsy photographs', 'fartsy things no like').and()"
```

```
Conditioning shape: torch.Size([1, 77, 4096])
NConditioning shape: torch.Size([1, 77, 2048])
Pooled shape: torch.Size([1, 1280])
NPooled shape: torch.Size([1, 1280])
```

not sure why that one needs to double its size at all when the other doesn't.

**Comment by damian0815** [comment]
@bghira i made a bunch of fixes to tensor padding and resizing just now - please check out latest `main` or `pip install compel==2.0.2.dev1` . see `compel-demo-sdxl.py` for reference, it demonstrates using `.and()` as well as batched usage of `compel([prompt_a, prompt_b])`

**Comment by skirsten** [comment]
Hi, I was running into the same issue, and tested yesterday with 2.0.1 and it was fine.
Today with 2.0.2.dev1 I am getting 
> huh. weird. please file a bug on the Compel github repo stating that "build_conditioning_tensor_for_conjunction shape has length 3". include your prompts and the code you use to invoke Compel.

when the negative prompt is longer than the positive prompt:
```
positive: this is a short prompt
negative: this is a long negative prompt, Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper rhoncus finibus. Nullam faucibus urna id magna dictum, sit amet tempor enim tristique. Cras tincidunt, mi quis cursus molestie, elit sem lacinia dolor, vel feugiat nulla ipsum sit amet magna. Suspendisse at elit neque. Fusce cursus, augue vitae ultricies rutrum, odio elit vulputate justo, eget iaculis elit mi in ex. Donec non odio fringilla, tristique nunc sit amet, porttitor enim. Sed sit amet mollis urna.
```

Now I wanted to fork the repo and try to improve the performance (is it normal that it takes ~500ms?) but it seems that the main branch does not work at all and is back to the old error:
```
The size of tensor a (177) must match the size of tensor b (77) at non-singleton dimension 1
```

It would be great if you could use GitHub releases or at least tags and push the code before pushing the release to pypi so we can understand the changes of the releases.

I am invoking compel like this (basically the same as `__call__,` but without the concat because I need it separate anyway).

```py
prompt_embeds, pooled_prompt_embeds = compel.build_conditioning_tensor(prompt)
negative_prompt_embeds, negative_pooled_prompt_embeds = compel.build_conditioning_tensor(negative_prompt)

[prompt_embeds, negative_prompt_embeds] = compel.pad_conditioning_tensors_to_same_length(
    conditionings=[prompt_embeds, negative_prompt_embeds]
)

```

**Comment by damian0815** [comment]
> It would be great if you could use GitHub releases or at least tags and push the code before pushing the release to pypi so we can understand the changes of the releases.

yeah, sorry about that, i know i've been lazy about it but i've just been putting off getting the Business Processes set up

**Comment by damian0815** [comment]
will try and make it a priority for v2.0.2 onwards

**Comment by damian0815** [comment]
fwiw as a stopgap you can use changes to the version string `pyproject.toml` as a proxy for the tags.

**Comment by Sur3** [comment]
I seem to have a related problem with compel-2.0.1-py3-none-any.whl, this code runs fine:

```
prompt = "outdoor photography, 8k, beautiful, caucasian, 1girl, (blonde)0.1, (redhead)0.1, pouty, cosplay, forest clearing"
negative_prompt = "drawing, anime, animation, manga, cartoon, ugly, blurry, tiling, disfigured, deformed, watermark, signature, underexposed, overexposed, sketch"

compel = Compel(tokenizer=[pipe.tokenizer, pipe.tokenizer_2] , text_encoder=[pipe.text_encoder, pipe.text_encoder_2], returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED, requires_pooled=[False, True], truncate_long_prompts=False)

prompt_embeds, pooled_prompt_embeds = compel.build_conditioning_tensor(prompt)
negative_prompt_embeds, negative_pooled_prompt_embeds = compel.build_conditioning_tensor(negative_prompt)

[prompt_embeds, negative_prompt_embeds] = compel.pad_conditioning_tensors_to_same_length(
    conditionings=[prompt_embeds, negative_prompt_embeds]
)
```

but as soon as I add .and() syntax changing the prompt like this:

`prompt = '("outdoor photography, 8k", "beautiful, caucasian, 1girl, (blonde)0.1, (redhead)0.1, pouty, cosplay", "forest clearing").and()'
`
I get this error:

```
Traceback (most recent call last):
  File "/home/neuron/system/sdxl-coding/./sdxl.py", line 48, in <module>
    [prompt_embeds, negative_prompt_embeds] = compel.pad_conditioning_tensors_to_same_length(
  File "/home/neuron/.local/lib/python3.10/site-packages/compel/compel.py", line 260, in pad_conditioning_tensors_to_same_length
    return type(self)._pad_conditioning_tensors_to_same_length(conditionings, emptystring_conditioning=emptystring_conditioning)
  File "/home/neuron/.local/lib/python3.10/site-packages/compel/compel.py", line 227, in _pad_conditioning_tensors_to_same_length
    raise ValueError(f"All conditioning tensors must have the same batch size ({c0_shape[0]}) and number of embeddings per token ({c0_shape[1]}")
ValueError: All conditioning tensors must have the same batch size (1) and number of embeddings per token (77
```

**Comment by ex10ded** [comment]
@Sur3 have you tried `pip install compel==2.0.2.dev1`? I had the exact same error as you before, and after upgrading from 2.0.1 it works as expected (at least no errors)

**Comment by Sur3** [comment]
Hi yes thanks updating to compel 2.0.2.dev1 fixes those problems. But I somehow run out of GPU memory when using

```
prompt_embeds, pooled_prompt_embeds = compel.build_conditioning_tensor(prompt)
negative_prompt_embeds, negative_pooled_prompt_embeds = compel.build_conditioning_tensor(negative_prompt)

```
instead of
```
prompt_embeds, pooled_prompt_embeds = compel(prompt)
negative_prompt_embeds, negative_pooled_prompt_embeds = compel(negative_prompt)
```

What's the difference between those two syntaxes?

**Comment by ex10ded** [comment]
> What's the difference between those two syntaxes?

my abilities start and end at upgrading pip packages ... @damian0815 ?

**Comment by damian0815** [comment]
good question, idk why you'd be getting a GPU OOM issue.

**Comment by damian0815** [comment]
please re-open if this is still an error with compel 2.0.2
