### ISSUE TITLE
Question does compel support lora load weight?

### ISSUE THREAD

**Issue by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [damian0815/compel#48]
i see <<Lora:testbigbrain:0.6>> in civitai quite often.I am curious is it directly supported in compel
or
does it need to be given when loading model which is another story for other lib.

**Comment by damian0815** [comment]
see discussion on #30

**Comment by cm5kZGV2MjAyM3B1YmdpdGh1YmFjYw** [comment]
huge thanks.
