### ISSUE TITLE
Can someone explain to me how this is different from normal weighted prompts that we've been using this entire time?

### ISSUE THREAD

**Issue by austin23cook** [damian0815/compel#5]
I read through all the documentation and it appears to be exactly the same to me

**Comment by damian0815** [comment]
do you mean the automatic1111 `((weighted))` syntax? that's specific to auto1111, it's not a stable diffusion core feature.

**Comment by anotherjesse** [comment]
@damian0815 sorry for the naive question, but does compel aim to support both automatic1111 style in addition to the style in compel?

I'm using diffuserslib and see users using automatic1111 style weights and am not sure if compel helps users get what they expect.

**Comment by anotherjesse** [comment]
It was easy enough to test this and see that it does support the invokeai style weights (as documented) but not the automatic1111 style weights:

    >>> compel_proc.parse_prompt_string("hello cat++")
    FlattenedPrompt:[Fragment:'hello'@1.0, Fragment:'cat'@1.2100000000000002]
    >>> compel_proc.parse_prompt_string("hello cat+++++")
    FlattenedPrompt:[Fragment:'hello'@1.0, Fragment:'cat'@1.6105100000000006]
    >>> compel_proc.parse_prompt_string("hello [[cat]]")
    FlattenedPrompt:[Fragment:'hello [[cat]]'@1.0]
    >>> compel_proc.parse_prompt_string("hello [[[cat]]]")
    FlattenedPrompt:[Fragment:'hello [[[cat]]]'@1.0]
    >>> compel_proc.parse_prompt_string("hello cat+++++")
    FlattenedPrompt:[Fragment:'hello'@1.0, Fragment:'cat'@1.6105100000000006]
    >>> compel_proc.parse_prompt_string("hello {{fire@4}}")
    FlattenedPrompt:[Fragment:'hello {{fire@4}}'@1.0]

As most users / prompt sites seem to use the automatic1111 style, I wonder if there is a way to support both styles.  Would a clean-room implementation patch of automatic1111 style be acceptable or is that not something this project wants to support?

**Comment by damian0815** [comment]
i think the best way to support auto111 syntax is a converter that converts to Compel syntax. such a thing already exists - https://gist.github.com/watzon/1e15172550a537532b0b52e12703aada . if this could be converted to a free function i could add it to Compel, but i have no intention of making auto111 syntax natively parseable
