### ISSUE TITLE
Is it possible to use compel with OpenVINO?

### ISSUE THREAD

**Issue by sjrummins** [damian0815/compel#50]
I am particularly interested in using it with OVStableDiffusionXLPipeline, as described here: https://huggingface.co/docs/diffusers/optimization/open_vino - ideally with negative prompts as well. Sorry, I know I'm asking a lot here!

I have previously committed some horrible hacks to coerce the non-XL OVStableDiffusionPipeline to more-or-less work with compel, but I haven't been able to make the XL pipeline work. I really don't know what I'm doing here; it is a case of cut, paste, tinker and hope. I had to go and edit files installed as part of the optimum/openvino packages to get the non-XL pipeline working, and even then I couldn't get .and() to work because the tensors had the wrong shape. The latest OpenVINO release does seem to be moving towards improved compatibility (I undid some but not all of my hacks for non-XL), but it still doesn't seem to be all the way there.

I've seen enough of how powerful compel can be that I'd really like to have it working properly with Stable Diffusion XL. Any advice would be appreciated!

**Comment by damian0815** [comment]
sorry, i can't really help. you should try writing shorter prompts.

**Comment by sjrummins** [comment]
Thanks, I will give that a try.

**Comment by clinty** [comment]
@sjrummins can you explain your non-XL hacks?
