### ISSUE TITLE
SDXL dual prompt example

### ISSUE THREAD

**Issue by pdoane** [damian0815/compel#51]
I have been able to use Compel for SDXL and SDXL-Refiner with a single prompt.  I'd like to test sending different prompts to the two text encoders for SDXL.

Is this supported yet?  If so, does someone have an example of it?

**Comment by damian0815** [comment]
you could spin up two separate Compel instances and use `torch.cat()` to concatenate the embeddings. you'll need the embedding to have a `.shape` of `[1, 77, 2048]` for it to work.

but to be clear, the base model at least already uses both text encoders, as does i believe the refiner. there's not one encoder for base and one for refiner. base and refiner both use both encoders.

**Comment by skirsten** [comment]
> base and refiner both use both encoders

Refiner only uses the second encoder, but its the same as the base.
See https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/tree/main and https://github.com/huggingface/diffusers/blob/ea5b0575f8f91b76f32fb6f6930c0bc30e42865e/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py#L298

**Comment by pdoane** [comment]
Thanks!  If anyone else is following and looking for an example:

```
compel1 = Compel(
    tokenizer=self.pipe.tokenizer,
    text_encoder=self.pipe.text_encoder,
    returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED,
    requires_pooled=False,
)

compel2 = Compel(
    tokenizer=self.pipe.tokenizer_2,
    text_encoder=self.pipe.text_encoder_2,
    returned_embeddings_type=ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NON_NORMALIZED,
    requires_pooled=True,
)

conditioning1 = compel1(prompt1)
conditioning2, pooled = compel2(prompt2)
conditioning = torch.cat((conditioning1, conditioning2), dim=-1)

image = pipeline(prompt_embeds=conditioning, pooled_prompt_embeds=pooled, num_inference_steps=30).images[0]
```

**Comment by damian0815** [comment]
is this resolved? can i close it?

**Comment by pdoane** [comment]
Might want to include the snippit in documentation, but yes I think we're good.

**Comment by damian0815** [comment]
thanks!
