### ISSUE TITLE
Does this work like lpw_stable_diffusion?

### ISSUE THREAD

**Issue by sarmientoj24** [damian0815/compel#54]
I can see that it is designed for weighted prompts. However, how does it deal with long prompts?

https://github.com/huggingface/diffusers/blob/main/examples/community/lpw_stable_diffusion.py

**Comment by damian0815** [comment]
idk how lpw_stable_diffusion works but if you pass `truncate_long_prompts=False` then it subdivides the prompt blindly into 75-token chunks. todo is better logic that splits on `,` or `.` or `;`
