### ISSUE TITLE
CLIP embeddings from Images

### ISSUE THREAD

**Issue by GuyARoss** [damian0815/compel#55]
How much work would it be to support CLIP embeddings from images? 

I am trying to get prompt embeddings to work for image embeddings for the hugging face pipeline, and thus far everyone has recommended this library.

**Comment by damian0815** [comment]
Unfortunately this won't work as (apart from the pooled embeds input to SDXL) SD is trained on the hidden states of the text encoder, which have shape `77x768` or `77x1280` or `77x2048` depending on which model you're using. there's no analog in the CLIP encoder - the pooled output is eg `1x768` and i don't know what the hidden states shape is but i'm certain it won't be compatible with what SD expects.
