### ISSUE TITLE
Clip Skip SDXL

### ISSUE THREAD

**Issue by adhikjoshi** [damian0815/compel#56]
As per docs we can do clip skip on SD 1.5 as below

> Please note that this is a breaking change if you've been using clip skip: the old boolean arg use_penultimate_clip_layer has been replaced with an enum ReturnedEmbeddingsType.PENULTIMATE_HIDDEN_STATES_NORMALIZED.

How can i do it for SDXL?

**Comment by damian0815** [comment]
not implemented for now
