### ISSUE TITLE
load negative_embeddings

### ISSUE THREAD

**Issue by cacko** [damian0815/compel#61]
is there a way to load negative_embeddings, for example let's say I have a negative prompt
`EasyNegativeV2 cartoon` where EasyNegativeV2 correspond to TI embedding file (https://civitai.com/models/100191?modelVersionId=107234) . If I load it thru the diffusers pipeline load_textual_inversion it actually does acts as normal prompt inversion instead of negative. Hope I am explaining understandable.
thanks

**Comment by damian0815** [comment]
yes, it's in the README - https://github.com/damian0815/compel/blob/d15e883bbbfae5b3fbd8d60065aa330c99a662b4/README.md#textual-inversion-support
