### ISSUE TITLE
Supporting separate SDXL CLIP G/L weighted prompts

### ISSUE THREAD

**Issue by subpanic** [damian0815/compel#63]
Currently it appears only possible to send any prompt to both SDXL text encoders with compel. Would be very useful to be able to send a different weighted prompt to each text encoder (such as using G for primary description and L for keyword/style emphasis).

**Comment by damian0815** [comment]
I just added an example to https://github.com/damian0815/compel/blob/main/compel-demo-sdxl.ipynb of doing this

**Comment by subpanic** [comment]
Thanks so much @damian0815 , sorry it's difficult to find things often spread among the repos
