### ISSUE TITLE
Is there anyway to debug the parsed prompt weight?

### ISSUE THREAD

**Issue by ynie** [damian0815/compel#73]
Hello, thanks for the awesome work. Is there anyway to print out the parsed prompt weights? For example, I had a typo(missing parenthesis) in the prompt and I didn't get any error. It would be great to actually print out the parsed weight so I can double check it? Thanks!

**Comment by damian0815** [comment]
you can use `compel.parse_prompt_string(prompt)` which returns a `Conjunction` (https://github.com/damian0815/compel/blob/main/doc/compel.md#parse_prompt_string) that you can then print:

```
conjunction = parse_prompt_string("my prompt")
print(conjunction)
# output: Conjunction:[FlattenedPrompt:[Fragment:'my prompt'@1.0]] | type AND | weights [1.0] | loras []
```
