### ISSUE TITLE
bug: s_start, s_end, t_start, t_end w/diffusers

### ISSUE THREAD

**Issue by JPPhoto** [damian0815/compel#8]
It looks like compel is setting values that aren't right for these terms when used in InvokeAI:

`{'s_start': 0.0, 's_end': 0.2062994740159002, 't_start': 0.0, 't_end': 1.0}`

`t_start` should be 0.2, and the `s_*` terms don't mean anything for diffusers.

**Comment by damian0815** [comment]
fixed in 57f5b2f
